language: go

go:
  - 1.11
  - 1.12
  - 1.13
  - 1.14
  - 1.15
  - tip

before_install:
  - go get -v -t -d ./...
  - if [[ $TRAVIS_GO_VERSION > 1.12 ]]; then GO111MODULE=on go get mvdan.cc/gofumpt; fi
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0

script:
  - if [[ $TRAVIS_GO_VERSION > 1.12 ]]; then test -z "$(gofumpt -l -s -d ./..)"; fi
  - golangci-lint run ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
