language: go

go:
  - 1.11
  - 1.12
  - 1.13
  - 1.14
  - 1.15
  - tip

before_install:
  - go get -v -t -d ./...
  - GO111MODULE=on go get mvdan.cc/gofumpt
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0

script:
  - gofumpt -w -s ./..
  - golangci-lint run ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
